# CMake generated Testfile for 
# Source directory: /home/runner/work/keepassxc/keepassxc/tests
# Build directory: /home/runner/work/keepassxc/keepassxc/_codeql_build_dir/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testgroup "testgroup")
set_tests_properties(testgroup PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;101;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkdbx2 "testkdbx2")
set_tests_properties(testkdbx2 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;104;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkdbx3 "testkdbx3")
set_tests_properties(testkdbx3 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;107;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkdbx4 "testkdbx4")
set_tests_properties(testkdbx4 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;110;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkeys "testkeys")
set_tests_properties(testkeys PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;113;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testgroupmodel "testgroupmodel")
set_tests_properties(testgroupmodel PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;116;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testentrymodel "testentrymodel")
set_tests_properties(testentrymodel PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;119;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testcryptohash "testcryptohash")
set_tests_properties(testcryptohash PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;122;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testsymmetriccipher "testsymmetriccipher")
set_tests_properties(testsymmetriccipher PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;125;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testhashedblockstream "testhashedblockstream")
set_tests_properties(testhashedblockstream PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;128;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkeepass2randomstream "testkeepass2randomstream")
set_tests_properties(testkeepass2randomstream PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;131;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testmodified "testmodified")
set_tests_properties(testmodified PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;134;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testdeletedobjects "testdeletedobjects")
set_tests_properties(testdeletedobjects PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;137;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testkeepass1reader "testkeepass1reader")
set_tests_properties(testkeepass1reader PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;140;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testimports "testimports")
set_tests_properties(testimports PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;143;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testautotype "testautotype")
set_tests_properties(testautotype PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;154;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testentry "testentry")
set_tests_properties(testentry PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;168;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testmerge "testmerge")
set_tests_properties(testmerge PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;171;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testpasswordgenerator "testpasswordgenerator")
set_tests_properties(testpasswordgenerator PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;174;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testpasswordhealth "testpasswordhealth")
set_tests_properties(testpasswordhealth PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;177;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testpassphrasegenerator "testpassphrasegenerator")
set_tests_properties(testpassphrasegenerator PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;180;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testhibp "testhibp")
set_tests_properties(testhibp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;183;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testtotp "testtotp")
set_tests_properties(testtotp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;186;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testbase32 "testbase32")
set_tests_properties(testbase32 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;189;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testcsvparser "testcsvparser")
set_tests_properties(testcsvparser PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;192;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testrandomgenerator "testrandomgenerator")
set_tests_properties(testrandomgenerator PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;195;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testentrysearcher "testentrysearcher")
set_tests_properties(testentrysearcher PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;198;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testcsvexporter "testcsvexporter")
set_tests_properties(testcsvexporter PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;201;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testdatabase "testdatabase")
set_tests_properties(testdatabase PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;215;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testtools "testtools")
set_tests_properties(testtools PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;218;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testconfig "testconfig")
set_tests_properties(testconfig PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;221;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
add_test(testcli "testcli")
set_tests_properties(testcli PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;75;add_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;249;add_unit_test;/home/runner/work/keepassxc/keepassxc/tests/CMakeLists.txt;0;")
